CREWS = (
    (0, '--- Please select ---'),
    (1, 'Accounting - 1st Assistant Accountant'),
    (2, 'Accounting - 1st Assistant Accountant - Payroll'),
    (3, 'Accounting - 2nd Assistant Accountant'),
    (4, 'Accounting - Production Accountant'),
    (128, 'Accounting - Post-Production Accountant'),
    (129, 'Accounting - Post-Production Assistant Accountant'),
    (5, 'Accounting - Trainee Assistant Accountant'),
    (6, 'Accounting - 3rd Assistant Accountant'),
    (7, 'Art Department - 1st Assistant Art Director'),
    (8, 'Art Department - 2nd Assistant Art Director'),
    (9, 'Art Department - 3rd Assistant Art Director'),
    (10, 'Art Department - Art Department Coordinator'),
    (11, 'Art Department - Art Director'),
    (12, 'Art Department - Graphic Artist  GRAPHIC'),
    (13, 'Art Department - Production Designer PD'),
    (14, 'Art Department - Trainee Assistant Art Director'),
    (15, 'Art Department - Storyboard Artist'),
    (16, 'Assistant Directors - 1st Assistant Director'),
    (17, 'Assistant Directors - Medic  / Set Medic'),
    (18, 'Assistant Directors - Set Production Assistant'),
    (19, 'Assistant Directors - Trainee Assistant Director/4th Assistant'),
    (20, 'Assistant Directors - 2nd Assistant Director'),
    (21, 'Assistant Directors - 2nd Unit Director'),
    (22, 'Assistant Directors - 3rd Assistant Director'),
    (23, 'Casting - Background Performer'),
    (24, 'Casting - Stand In'),
    (25, 'Camera - 1st Assistant Camera'),
    (26, 'Camera - Camera Operator'),
    (27, 'Camera - Camera Trainee'),
    (28, 'Camera - Data Imaging Technician'),
    (29, 'Camera - Data Management Technician'),
    (30, 'Camera - Director of Photography/Cinematographer'),
    (31, 'Camera - Stand In'),
    (32, 'Camera - 2nd Assistant Camera'),
    (33, 'Casting - Casting Director'),
    (34, 'Casting - Extras Casting'),
    (35, 'Catering & Craft - Catering'),
    (36, 'Catering & Craft - Craft Service'),
    (37, 'Construction - Carpenter'),
    (38, 'Construction - Scenic Artist/Painter'),
    (39, 'Continuity - Script Supervisor'),
    (40, 'Electric / Lighting - Best Boy Electric'),
    (41, 'Electric / Lighting - Electric'),
    (42, 'Electric / Lighting - Gaffer'),
    (43, 'Electric / Lighting - Genny Op'),
    (44, 'Grip - Best Boy Grip'),
    (45, 'Grip - Dolly Grip'),
    (46, 'Grip - Grip'),
    (47, 'Grip - Key Grip'),
    (48, 'Hair & Make Up - Assistant Hair'),
    (49, 'Hair & Make Up - Assistant Make Up'),
    (50, 'Hair & Make Up - Hair'),
    (51, 'Hair & Make Up - Make Up'),
    (52, 'Hair & Make Up - SPFX Make Up'),
    (53, 'Locations - Assistant Location Manager'),
    (130, 'Locations - Key Locations Support (Security)'),
    (54, 'Locations - Location Manager'),
    (55, 'Locations - Location Production Assistant'),
    (56, 'Locations - Location Scout'),
    (57, 'Locations - Location Support Personnel/Security'),
    (58, 'Locations - Trainee Location Manager'),
    (59, 'Post-Production - 1st Assistant Picture Editor'),
    (131, 'Post-Production - Accountant'),
    (132, 'Post-Production - Assistant Accountant'),
    (60, 'Post-Production - Composer'),
    (70, 'Post-Production - Dialogue Editor'),
    (71, 'Post-Production - Music Editor'),
    (72, 'Post-Production - Picture Editor'),
    (73, 'Post-Production - Post Production Assistant'),
    (74, 'Post-Production - Post Production Supervisor'),
    (75, 'Post-Production - Sound Editor'),
    (76, 'Post-Production - Trainee Assistant Editor'),
    (77, 'Post-Production - 1st Assistant Sound Editor'),
    (78, 'Post-Production - 2nd Assistant Picture Editor'),
    (79, 'Post-Production - 2nd Assistant Sound Editor'),
    (80, 'Production - Assistant Production Coordinator'),
    (81, 'Production - Assistant Production Manager'),
    (82, 'Production - Associate Producer'),
    (83, 'Production - Director'),
    (84, 'Production - Directors Assistant'),
    (85, 'Production - Executive Producer'),
    (86, 'Production - Line Producer'),
    (87, 'Production - Producer'),
    (88, 'Production - Producers Assistant'),
    (89, 'Production - Production Coordinator'),
    (90, 'Production - Production Manager'),
    (91, 'Production - Production Secretary'),
    (92, 'Production - Researcher'),
    (93, 'Production - Tutor/Set Teacher'),
    (94, 'Production - Unit Manager'),
    (95, 'Production - Unit Production Manager'),
    (96, 'Production - Co-Producer'),
    (97, 'Production - Office Production Assistant'),
    (126, 'Production - Production Associate'),
    (127, 'Production - Production Liason'),
    (98, 'Props - Assistant Props Master'),
    (99, 'Props - Props Buyer'),
    (100, 'Props - Props Master'),
    (101, 'Props - Armourer'),
    (102, 'Publicity - EPK/Behind the Scenes Videographer'),
    (103, 'Publicity - Stills Photographer'),
    (104, 'Set Decoration - Assistant Set Decorator'),
    (105, 'Set Decoration - Set Dec Buyer'),
    (106, 'Set Decoration - Set Decorator'),
    (107, 'Set Decoration - Set Dresser'),
    (108, 'Sound - Boom Op'),
    (109, 'Sound - Cable Puller'),
    (110, 'Sound - Sound Mixer'),
    (111, 'Special FX - Effects Editor'),
    (112, 'Special FX - SPFX Coordinator'),
    (113, 'Special FX - SPFX Technician'),
    (114, 'Stunts - Stunt Coordinator'),
    (115, 'Stunts - Stunt Performer'),
    (133, 'Transport - Cast Driver'),
    (116, 'Transport - Driver'),
    (134, 'Transport - Picture Car Driver'),
    (117, 'Transport - Picture Cars Captain'),
    (118, 'Transport - Transport Captain'),
    (119, 'Transport - Transport Coordinator'),
    (135, 'Transport - Unit Driver'),
    (120, 'Wardrobe & Costumes - Costume Buyer'),
    (121, 'Wardrobe & Costumes - Costume Designer'),
    (122, 'Wardrobe & Costumes - Assistant Costume Designer (& Set Jobs)'),
    (123, 'Writers - Writer'),
    (124, 'Animals - Animal Wrangler'),
    (125, 'Other - Other'),
)